version: '3.8'

services:
    consumer:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        command: php bin/console app:consume-events -vvv
        depends_on:
            - redis
        environment:
            COMPOSER_MEMORY_LIMIT: -1
            REDIS_HOST: redis
            REDIS_PORT: 6379
        deploy:
            replicas: 3
    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
    event-source-1:
        build:
            context: ./event-api-mock
        environment:
            - SERVER_FILE=server1.js
        ports:
            - "3001:3001"

    event-source-2:
        build:
            context: ./event-api-mock
        environment:
            - SERVER_FILE=server2.js
        ports:
            - "3002:3002"

    event-source-3:
        build:
            context: ./event-api-mock
        environment:
            - SERVER_FILE=server3.js
        ports:
            - "3003:3003"
volumes:
    redis-data: